name: Update sheets_data.json from Google Sheets!

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (UTC)
  workflow_dispatch:       # Optional manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run getdata.py
        run: python getdata.py

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add sheets_data.json
          if ! git diff --cached --quiet; then
            git commit -m "Auto-update sheets_data.json"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          else
            echo "No changes to commit."
          fi